
Current configuration for extension with alias "monolog_poc"
============================================================

monolog_poc:
    use_microseconds: true
    channels:
        - hello
    handlers:
        my_handler_1:
            native_mailer:
                from_email: from_email@native_mailer.com
                to_email:
                    - to_email@native_mailer.com
                subject: 'subject native_mailer'
                level: ERROR
                channels:
                    type: inclusive
                    elements:
                        - hello
                headers: {  }
                process_psr_3_messages:
                    enabled: null
                bubble: true
                nested: false

