# Copy this file in app/config/packages
poc:
    a: false
    b: value_b
    c: false
    d:
        sub_d: false
    e:
        id: ~
        host: ~
        port: 9200
        transport: ~
        user: null
        password: null
    f:
        id: ~
        host: ~
        port: 9200
        transport: ~
    g:
        id: ~
        host: ~
        port: 9200
        transport: ~
        user: null
        password: null
    h: false
    services:
        type: type_a

