Error {#7669
  #message: "Call to a member function fragments() on null"
  #code: 0
  #file: "/home/jeriv/Repo/contributing/monolog-bundle-dynamic-config-node-with-app-for-testing/monolog-poc-bundle/src/DependencyInjection/AddConfiguration/StreamHandlerConfiguration.php"
  #line: 16
  trace: {
    /home/jeriv/Repo/contributing/monolog-bundle-dynamic-config-node-with-app-for-testing/monolog-poc-bundle/src/DependencyInjection/AddConfiguration/StreamHandlerConfiguration.php:16 {
      Local\Bundle\MonologPocBundle\DependencyInjection\AddConfiguration\StreamHandlerConfiguration->__invoke(Symfony\Component\Config\Definition\Builder\NodeDefinition|Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition|Symfony\Component\Config\Tests\Fixtures\Builder\VariableNodeDefinition $node): void
      › ->fragments()->path()
      › ->fragments()->filePermission()
      › ->fragments()->useLocking()
    }
    /home/jeriv/Repo/contributing/monolog-bundle-dynamic-config-node-with-app-for-testing/monolog-poc-bundle/src/Definition/Builder/NodeBuilder.php:63 { …}
    /home/jeriv/Repo/contributing/monolog-bundle-dynamic-config-node-with-app-for-testing/monolog-poc-bundle/src/DependencyInjection/Configuration.php:40 { …}
    /home/jeriv/Repo/contributing/monolog-bundle-dynamic-config-node-with-app-for-testing/monolog-poc-bundle/src/Definition/Builder/NodeBuilder.php:35 { …}
    /home/jeriv/Repo/contributing/monolog-bundle-dynamic-config-node-with-app-for-testing/monolog-poc-bundle/src/DependencyInjection/Configuration.php:33 { …}
    /home/jeriv/Repo/contributing/monolog-bundle-dynamic-config-node-with-app-for-testing/symfony/src/Symfony/Component/Config/Definition/Processor.php:46 { …}
    /home/jeriv/Repo/contributing/monolog-bundle-dynamic-config-node-with-app-for-testing/symfony/src/Symfony/Component/DependencyInjection/Compiler/ValidateEnvPlaceholdersPass.php:74 { …}
    /home/jeriv/Repo/contributing/monolog-bundle-dynamic-config-node-with-app-for-testing/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:73 { …}
    /home/jeriv/Repo/contributing/monolog-bundle-dynamic-config-node-with-app-for-testing/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:814 { …}
    /home/jeriv/Repo/contributing/monolog-bundle-dynamic-config-node-with-app-for-testing/symfony/src/Symfony/Component/HttpKernel/Kernel.php:499 { …}
    /home/jeriv/Repo/contributing/monolog-bundle-dynamic-config-node-with-app-for-testing/symfony/src/Symfony/Component/HttpKernel/Kernel.php:744 { …}
    /home/jeriv/Repo/contributing/monolog-bundle-dynamic-config-node-with-app-for-testing/symfony/src/Symfony/Component/HttpKernel/Kernel.php:120 { …}
    /home/jeriv/Repo/contributing/monolog-bundle-dynamic-config-node-with-app-for-testing/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:177 { …}
    /home/jeriv/Repo/contributing/monolog-bundle-dynamic-config-node-with-app-for-testing/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:69 { …}
    /home/jeriv/Repo/contributing/monolog-bundle-dynamic-config-node-with-app-for-testing/symfony/src/Symfony/Component/Console/Application.php:193 { …}
    /home/jeriv/Repo/contributing/monolog-bundle-dynamic-config-node-with-app-for-testing/symfony/src/Symfony/Component/Runtime/Runner/Symfony/ConsoleApplicationRunner.php:49 { …}
    ./vendor/autoload_runtime.php:29 { …}
    ./bin/console:15 { …}
  }
}
