# Default configuration for extension with alias: "monolog_poc"
monolog-poc:
    use_microseconds:     true
    channels:             []
    handlers:

        # All "stream" type handlers
        stream:

            # Prototype
            name:
                path:                 '%kernel.logs_dir%/%kernel.environment%.log'
                level:                DEBUG
                bubble:               true
                file_permission:      null
                use_locking:          false
                channels:
                    type:                 ~
                    elements:             []

        # All "console" type handlers
        console:

            # Prototype
            name:
                verbosity_levels:
                    VERBOSITY_QUIET:      ERROR
                    VERBOSITY_NORMAL:     WARNING
                    VERBOSITY_VERBOSE:    NOTICE
                    VERBOSITY_VERY_VERBOSE: INFO
                    VERBOSITY_DEBUG:      DEBUG
                level:                DEBUG
                bubble:               true
                console_formatter_options: []
                channels:
                    type:                 ~
                    elements:             []

        # All "firephp" type handlers
        firephp:

            # Prototype
            name:
                level:                DEBUG
                bubble:               true

        # All "rotating_file" type handlers
        rotating_file:

            # Prototype
            name:
                path:                 '%kernel.logs_dir%/%kernel.environment%.log'
                level:                DEBUG
                bubble:               true
                file_permission:      null
                use_locking:          false
                filename_format:      '{filename}-{date}'
                date_format:          Y-m-d
                channels:
                    type:                 ~
                    elements:             []

        # All "swift_mailer" type handlers
        swift_mailer:

            # Prototype
            name:
                from_email:           ~
                to_email:             []
                subject:              ~
                content_type:         null
                headers:              []
                mailer:               null
                email_prototype:
                    id:                   ~ # Required
                    method:               null
                level:                DEBUG
                bubble:               true
                lazy:                 true

        # All "native_mailer" type handlers
        native_mailer:

            # Prototype
            name:
                from_email:           ~
                to_email:             []
                subject:              ~
                content_type:         null
                headers:              []
                mailer:               null
                email_prototype:
                    id:                   ~ # Required
                    method:               null
                level:                DEBUG
                bubble:               true
                lazy:                 true

        # All "symfony_mailer" type handlers
        symfony_mailer:

            # Prototype
            name:
                from_email:           ~
                to_email:             []
                subject:              ~
                content_type:         null
                headers:              []
                mailer:               null
                email_prototype:
                    id:                   ~ # Required
                    method:               null
                level:                DEBUG
                bubble:               true
                lazy:                 true

