# Default configuration for extension with alias: "monolog_poc"
monolog-poc:
    use_microseconds:     true
    channels:             []
    handlers:

        # All type "stream" handlers
        stream:

            # Prototype
            name:                 []

        # All type "console" handlers
        console:

            # Prototype
            name:                 []

        # All type "firephp" handlers
        firephp:

            # Prototype
            name:                 []

