# Default configuration for extension with alias: "monolog_poc"
monolog-poc:
    use_microseconds:     true
    channels:             []
    handlers:

        # All type "stream" handlers
        stream:

            # Prototype
            name:
                path:                 '%kernel.logs_dir%/%kernel.environment%.log'
                level:                DEBUG
                bubble:               true
                file_permission:      null
                use_locking:          false

        # All type "console" handlers
        console:

            # Prototype
            name:
                verbosity_levels:
                    VERBOSITY_QUIET:      ERROR
                    VERBOSITY_NORMAL:     WARNING
                    VERBOSITY_VERBOSE:    NOTICE
                    VERBOSITY_VERY_VERBOSE: INFO
                    VERBOSITY_DEBUG:      DEBUG
                level:                DEBUG
                bubble:               true
                console_formatter_options: []

        # All type "firephp" handlers
        firephp:

            # Prototype
            name:
                level:                DEBUG
                bubble:               true

