# Default configuration for extension with alias: "monolog_poc"
monolog-poc:
    use_microseconds:     true
    channels:             []
    handlers:

        # All type "stream" handlers
        stream:

            # Prototype
            name:
                option_3:             ~
                option_5:             ~

        # All type "console" handlers
        console:

            # Prototype
            name:
                option_7:             ~
                option_8:             ~

