# Default configuration for extension with alias: "monolog_poc"
monolog-poc:
    use_microseconds:     true
    channels:             []
    handlers:

        # All type "amqp" handlers
        amqp:

            # Prototype
            name:                 []

        # All type "browser_console" handlers
        browser_console:

            # Prototype
            name:                 []

        # All type "buffer" handlers
        buffer:

            # Prototype
            name:                 []

        # All type "chromephp" handlers
        chromephp:

            # Prototype
            name:                 []

        # All type "console" handlers
        console:

            # Prototype
            name:                 []

        # All type "cube" handlers
        cube:

            # Prototype
            name:                 []

        # All type "debug" handlers
        debug:

            # Prototype
            name:                 []

        # All type "deduplication" handlers
        deduplication:

            # Prototype
            name:                 []

        # All type "elastica" handlers
        elastica:

            # Prototype
            name:                 []

        # All type "elastic_search" handlers
        elastic_search:

            # Prototype
            name:                 []

        # All type "error_log" handlers
        error_log:

            # Prototype
            name:                 []

        # All type "fallbackgroup" handlers
        fallbackgroup:

            # Prototype
            name:                 []

        # All type "filter" handlers
        filter:

            # Prototype
            name:                 []

        # All type "fingers_crossed" handlers
        fingers_crossed:

            # Prototype
            name:                 []

        # All type "firephp" handlers
        firephp:

            # Prototype
            name:                 []

        # All type "gelf" handlers
        gelf:

            # Prototype
            name:                 []

        # All type "group" handlers
        group:

            # Prototype
            name:                 []

        # All type "hipchat" handlers
        hipchat:

            # Prototype
            name:                 []

        # All type "loggly" handlers
        loggly:

            # Prototype
            name:                 []

        # All type "mongo" handlers
        mongo:

            # Prototype
            name:                 []

        # All type "native_mailer" handlers
        native_mailer:

            # Prototype
            name:                 []

        # All type "newrelic" handlers
        newrelic:

            # Prototype
            name:                 []

        # All type "null" handlers
        null:

            # Prototype
            name:                 []

        # All type "predis" handlers
        predis:

            # Prototype
            name:                 []

        # All type "pushover" handlers
        pushover:

            # Prototype
            name:                 []

        # All type "raven" handlers
        raven:

            # Prototype
            name:                 []

        # All type "redis" handlers
        redis:

            # Prototype
            name:                 []

        # All type "rotating_file" handlers
        rotating_file:

            # Prototype
            name:                 []

        # All type "sentry" handlers
        sentry:

            # Prototype
            name:                 []

        # All type "slack" handlers
        slack:

            # Prototype
            name:                 []

        # All type "slackbot" handlers
        slackbot:

            # Prototype
            name:                 []

        # All type "slackwebhook" handlers
        slackwebhook:

            # Prototype
            name:                 []

        # All type "socket" handlers
        socket:

            # Prototype
            name:                 []

        # All type "stream" handlers
        stream:

            # Prototype
            name:                 []

        # All type "swift_mailer" handlers
        swift_mailer:

            # Prototype
            name:                 []

        # All type "symfony_mailer" handlers
        symfony_mailer:

            # Prototype
            name:                 []

        # All type "syslog" handlers
        syslog:

            # Prototype
            name:                 []

        # All type "syslogudp" handlers
        syslogudp:

            # Prototype
            name:                 []

        # All type "test" handlers
        test:

            # Prototype
            name:                 []

        # All type "whatfailuregroup" handlers
        whatfailuregroup:

            # Prototype
            name:                 []

