# Default configuration for extension with alias: "poc"
poc:

    # info a
    a:                    true

    # info b
    b:                    default

    # info c
    c:                    true

    # info d
    d:
        sub_d:                true

    # info e
    e:
        id:                   ~
        host:                 ~
        port:                 9200
        transport:            ~
        user:                 null
        password:             null

    # info f
    f:
        id:                   ~
        host:                 ~
        port:                 9200
        transport:            ~

    # info g
    g:
        id:                   ~
        host:                 ~
        port:                 9200
        transport:            ~
        user:                 null
        password:             null

    # info h
    h:                    true
    services:

        # Prototype: info services
        name:                 ~

