
Current configuration for extension with alias "monolog_poc"
============================================================

monolog_poc:
    channels:
        - deprecation
    handlers:
        main:
            fingers_crossed:
                action_level: error
                handler: nested
                excluded_http_codes:
                    -
                        code: 404
                        urls: {  }
                    -
                        code: 405
                        urls: {  }
                    -
                        code: 404
                        urls: {  }
                    -
                        code: 405
                        urls: {  }
                channels:
                    type: exclusive
                    elements:
                        - event
                buffer_size: 50
                activation_strategy: null
                excluded_404s: {  }
                stop_buffering: true
                passthru_level: null
                bubble: true
                process_psr_3_messages:
                    enabled: null
                level: DEBUG
                nested: false
        stream:
            stream:
                path: /app/var/log/prod.log
                level: debug
                channels:
                    type: exclusive
                    elements:
                        - event
                file_permission: null
                use_locking: false
                process_psr_3_messages:
                    enabled: null
                bubble: true
                nested: false
        console:
            console:
                process_psr_3_messages:
                    enabled: false
                channels:
                    type: exclusive
                    elements:
                        - event
                        - doctrine
                        - console
                console_formatter_options: {  }
                level: DEBUG
                bubble: true
                nested: false
        nested:
            stream:
                path: 'php://stderr'
                level: debug
                formatter: monolog_poc.formatter.json
                file_permission: null
                use_locking: false
                process_psr_3_messages:
                    enabled: null
                bubble: true
                nested: false
        deprecation:
            stream:
                channels:
                    type: inclusive
                    elements:
                        - deprecation
                path: 'php://stderr'
                formatter: monolog_poc.formatter.json
                file_permission: null
                use_locking: false
                process_psr_3_messages:
                    enabled: null
                level: DEBUG
                bubble: true
                nested: false
    use_microseconds: true

