monolog_poc:
    use_microseconds: true
    channels: ['hello']
    handlers:
        my_handler_1:
            swift_mailer:
                from_email: email@swift_mailer.com
                to_email: [to_email@swift_mailer.com]
                subject: 'subject swift_mailer'
                level: DEBUG
                channels: ['hello']

when@dev:
    monolog_poc: ~

when@prod:
    monolog_poc:
        handlers:
            my_handler_1:
                native_mailer:
                    from_email: from_email@native_mailer.com
                    to_email: [to_email@native_mailer.com]
                    subject: 'subject native_mailer'
                    level: ERROR
                    channels: ['hello']
