
Current configuration for extension with alias "monolog_poc"
============================================================

monolog_poc:
    channels:
        - deprecation
    handlers:
        main:
            fingers_crossed:
                action_level: error
                handler: nested
                excluded_http_codes:
                    -
                        code: 404
                        urls: {  }
                    -
                        code: 405
                        urls: {  }
                channels:
                    type: exclusive
                    elements:
                        - event
                activation_strategy: null
                excluded_404s: {  }
                buffer_size: 0
                stop_buffering: true
                passthru_level: null
                bubble: true
                process_psr_3_messages:
                    enabled: null
                level: DEBUG
                nested: false
        nested:
            stream:
                path: /app/var/log/test.log
                level: debug
                file_permission: null
                use_locking: false
                process_psr_3_messages:
                    enabled: null
                bubble: true
                nested: false
    use_microseconds: true

