
Current configuration for extension with alias "monolog"
========================================================

monolog:
    channels:
        - deprecation
    handlers:
        main:
            action_level: error
            handler: nested
            excluded_http_codes:
                -
                    code: 404
                    urls: {  }
                -
                    code: 405
                    urls: {  }
            channels:
                type: exclusive
                elements:
                    - event
            type: fingers_crossed
            priority: 0
            level: DEBUG
            bubble: true
            include_stacktraces: false
            nested: false
            exchange_name: log
            buffer_size: 0
            flush_on_overflow: false
            process_psr_3_messages:
                enabled: null
            console_formatter_options: {  }
            time: 60
            deduplication_level: 400
            store: null
            index: monolog
            document_type: logs
            ignore_error: false
            message_type: 0
            members: {  }
            accepted_levels: {  }
            min_level: DEBUG
            max_level: EMERGENCY
            activation_strategy: null
            stop_buffering: true
            passthru_level: null
            excluded_404s: {  }
            message_format: text
            api_version: null
            notify: false
            nickname: Monolog
            use_ssl: true
            host: null
            tags: {  }
            to_email: {  }
            headers: {  }
            app_name: null
            title: null
            client_id: null
            auto_log_stacks: false
            release: null
            environment: null
            config: {  }
            path: app/var/log/test.log
            max_files: 0
            file_permission: null
            use_locking: false
            filename_format: '{filename}-{date}'
            date_format: Y-m-d
            factor: 1
            fill_extra_context: false
            hub_id: null
            channel: null
            bot_name: Monolog
            use_attachment: true
            use_short_attachment: false
            include_extra: false
            icon_emoji: null
            content_type: null
            mailer: null
            lazy: true
            ident: false
            facility: user
            logopts: 1
            port: 514
            parse_mode: null
            disable_webpage_preview: null
            disable_notification: null
            split_long_messages: false
            delay_between_messages: false
        nested:
            path: app/var/log/test.log
            level: debug
            type: stream
            priority: 0
            bubble: true
            include_stacktraces: false
            nested: false
            exchange_name: log
            buffer_size: 0
            flush_on_overflow: false
            process_psr_3_messages:
                enabled: null
            console_formatter_options: {  }
            time: 60
            deduplication_level: 400
            store: null
            index: monolog
            document_type: logs
            ignore_error: false
            message_type: 0
            members: {  }
            accepted_levels: {  }
            min_level: DEBUG
            max_level: EMERGENCY
            action_level: WARNING
            activation_strategy: null
            stop_buffering: true
            passthru_level: null
            excluded_404s: {  }
            excluded_http_codes: {  }
            message_format: text
            api_version: null
            notify: false
            nickname: Monolog
            use_ssl: true
            host: null
            tags: {  }
            to_email: {  }
            headers: {  }
            app_name: null
            title: null
            client_id: null
            auto_log_stacks: false
            release: null
            environment: null
            config: {  }
            max_files: 0
            file_permission: null
            use_locking: false
            filename_format: '{filename}-{date}'
            date_format: Y-m-d
            factor: 1
            fill_extra_context: false
            hub_id: null
            channel: null
            bot_name: Monolog
            use_attachment: true
            use_short_attachment: false
            include_extra: false
            icon_emoji: null
            content_type: null
            mailer: null
            lazy: true
            ident: false
            facility: user
            logopts: 1
            port: 514
            parse_mode: null
            disable_webpage_preview: null
            disable_notification: null
            split_long_messages: false
            delay_between_messages: false
    use_microseconds: true

